Repository st-tiendinh/remix-calendar, pull requests merged in 2023-11, with the labels that each got.

#1 [Task] Init Source
  .DS_Store
  .eslintrc.cjs
  .gitignore
  README.md
  app/.DS_Store
  app/entry.client.tsx
  app/entry.server.tsx
  app/root.tsx
  app/routes/_index.tsx
  app/server/prisma.server.ts
  app/styles/app.css
  package-lock.json
  package.json
  postcss.config.js
  prisma/schema.prisma
  public/.DS_Store
  public/favicon.ico
  remix.config.js
  remix.env.d.ts
  styles/app.css
  tailwind.config.js
  tsconfig.json
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#2 [Task] Connect db and install mongodb
  package-lock.json
  package.json
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#3 [Task] Config prettier
  .prettierrc
  package-lock.json
  package.json
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#5 Setup sass
  app/.DS_Store
  app/routes/_index.tsx
  app/styles/app.css
  app/styles/app.css.map
  package-lock.json
  package.json
  postcss.config.js
  styles/app.css
  stylesheet/base/_all.scss
  stylesheet/base/_base.scss
  stylesheet/base/_extends.scss
  stylesheet/base/_mixins.scss
  stylesheet/base/_reset.scss
  stylesheet/base/_variables.scss
  stylesheet/layout/_all.scss
  stylesheet/modules/_all.scss
  stylesheet/pages/_all.scss
  stylesheet/pages/_users.scss
  stylesheet/state/_all.scss
  stylesheet/state/_space.scss
  stylesheet/state/_text.scss
  stylesheet/styles.scss
  tailwind.config.js
Labels: [Priority] 01 - Urgent, [Status] 03 - Review needed, [Type] Task

#4 [Task] Design and write schema for user table
  prisma/schema.prisma
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#10 [Task]Design and create prisma shcema for event table
  prisma/schema.prisma
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#12 Validate form login
  .gitignore
  app/components/form-field.tsx
  app/routes/login.tsx
  app/shared/components/FormField.tsx
  app/shared/utils/validators.serve.ts
  app/styles/app.css
  app/styles/app.css.map
  stylesheet/pages/_login.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#11 [Task] Create login & register API
  app/routes/_index.tsx
  app/routes/login.tsx
  app/server/auth.server.ts
  app/server/prisma.server.ts
  app/server/user.server.ts
  app/utils/types.server.ts
  app/utils/validators.server.ts
  package-lock.json
  package.json
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#9 Create UI page login
  .gitignore
  app/routes/login.tsx
  app/shared/components/FormField.tsx
  app/shared/utils/validators.serve.ts
  app/styles/app.css
  app/styles/app.css.map
  assets/.DS_Store
  assets/icons/.DS_Store
  assets/icons/ic-password.svg
  assets/icons/ic-username.svg
  assets/images/.DS_Store
  assets/images/login-bg.jpg
  stylesheet/base/_base.scss
  stylesheet/base/_variables.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_icons.scss
  stylesheet/pages/_all.scss
  stylesheet/pages/_login.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#13 [Task] Create custom form using remix-form
  app/server/formAction.server.ts
  app/shared/components/form.tsx
  package-lock.json
  package.json
Labels: [Priority] 02 - High, [Status] 05 - Done, [Type] Task

#15 Config grid layout
  .github/pull_request_template.md
  package-lock.json
  stylesheet/base/_mixins.scss
  stylesheet/base/_variables.scss
  stylesheet/layout/_grid.scss
Labels: [Priority] 01 - Urgent, [Status] 03 - Review needed, [Type] Task

#16 [Task] Modify form and implement api for login
  app/root.tsx
  app/routes/login.tsx
  app/server/auth.server.ts
  app/styles/app.css
  app/styles/app.css.map
  package-lock.json
  package.json
  stylesheet/base/_reset.scss
  stylesheet/base/_variables.scss
  stylesheet/pages/_login.scss
Labels: [Priority] 03 - Low, [Status] 03 - Review needed, [Type] Task

#7 [Task] Create calendar UI component
  app/routes/_index.tsx
  app/shared/components/CalendarWrapper.tsx
  app/styles/app.css
  app/styles/app.css.map
  package-lock.json
  package.json
  stylesheet/base/_reset.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_calendar.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#17 [Story-1] As an Admin, I want to login before creating events
  .DS_Store
  .gitignore
  app/.DS_Store
  app/root.tsx
  app/routes/_index.tsx
  app/routes/login.tsx
  app/server/auth.server.ts
  app/server/prisma.server.ts
  app/server/user.server.ts
  app/shared/components/FormField.tsx
  app/shared/constant/validator.ts
  app/shared/utils/types.server.ts
  app/shared/utils/validators.server.ts
  app/styles/app.css
  app/styles/app.css.map
  assets/icons/ic-password.svg
  assets/icons/ic-username.svg
  assets/images/login-bg.jpg
  package-lock.json
  package.json
  prisma/schema.prisma
  public/.DS_Store
  remix.config.js
  stylesheet/base/_base.scss
  stylesheet/base/_reset.scss
  stylesheet/base/_variables.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_icons.scss
  stylesheet/pages/_all.scss
  stylesheet/pages/_login.scss
Labels: [Priority] 02 - High, [Type] Task, [Status] 06 - Request change

#14 Create UI new event
  app/routes/_index.tsx
  app/routes/event.create.tsx
  app/routes/event.tsx
  app/shared/components/FormEvent.tsx
  app/styles/app.css
  app/styles/app.css.map
  assets/icons/ic-arrow-left.svg
  assets/icons/ic-list.svg
  stylesheet/base/_base.scss
  stylesheet/base/_variables.scss
  stylesheet/layout/_all.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_form.scss
  stylesheet/modules/_icon.scss
  stylesheet/pages/_all.scss
  stylesheet/pages/_home.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#21 [Task] Create update event api
  app/routes/event.$eventId.tsx
  app/routes/event.$eventId_.edit.tsx
  app/routes/event.create.tsx
  app/routes/event.tsx
  app/server/auth.server.ts
  app/server/event.server.ts
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/FormEvent.tsx
  app/shared/utils/types.server.ts
  app/shared/utils/validators.server.ts
  app/styles/app.css
  app/styles/app.css.map
  package-lock.json
  package.json
  prisma/schema.prisma
  stylesheet/base/_reset.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_calendar.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#20 [Story-2] Admin create new event
  app/routes/_index.tsx
  app/routes/event.create.tsx
  app/routes/event.tsx
  app/routes/login.tsx
  app/server/auth.server.ts
  app/server/event.server.ts
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/FormEvent.tsx
  app/shared/utils/types.server.ts
  app/shared/utils/validators.server.ts
  app/styles/app.css
  app/styles/app.css.map
  package-lock.json
  package.json
  stylesheet/base/_reset.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_calendar.scss
Labels: [Priority] 02 - High, [Type] Task, [Status] 07 - Fixed

#22 [Story-3] Admin update event
  app/routes/_index.tsx
  app/routes/event.$eventId.tsx
  app/routes/event.$eventId_.edit.tsx
  app/routes/event.create.tsx
  app/routes/event.tsx
  app/routes/login.tsx
  app/server/auth.server.ts
  app/server/event.server.ts
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/FormEvent.tsx
  app/shared/utils/types.server.ts
  app/shared/utils/validators.server.ts
  app/styles/app.css
  app/styles/app.css.map
  package-lock.json
  package.json
  prisma/schema.prisma
  stylesheet/base/_reset.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_calendar.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#19 [Story-4] Create UI delete event
  app/server/event.server.ts
  app/shared/components/FormEvent.tsx
  assets/icons/ic-trash.svg
  stylesheet/modules/_icon.scss
  stylesheet/pages/_home.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#23 [Story-4] As a user , I can delete event
  app/routes/event.$eventId_.delete.tsx
  app/routes/event.$eventId_.edit.tsx
  app/routes/event.create.tsx
  app/routes/event.tsx
  app/server/event.server.ts
  app/shared/components/FormEvent.tsx
  app/shared/utils/types.server.ts
  app/styles/app.css
  app/styles/app.css.map
  assets/icons/ic-trash.svg
  stylesheet/modules/_icon.scss
  stylesheet/pages/_home.scss
Labels: [Priority] 01 - Urgent, [Status] 03 - Review needed, [Type] Task

#25 [Sprint-1] Sprint 1
  app/routes/_index.tsx
  app/routes/event.$eventId.tsx
  app/routes/event.$eventId_.delete.tsx
  app/routes/event.$eventId_.edit.tsx
  app/routes/event.create.tsx
  app/routes/event.tsx
  app/server/event.server.ts
  app/shared/components/FormEvent.tsx
  app/shared/utils/types.server.ts
  app/styles/app.css
  app/styles/app.css.map
  assets/icons/ic-trash.svg
  package-lock.json
  prisma/schema.prisma
  stylesheet/base/_reset.scss
  stylesheet/modules/_icon.scss
  stylesheet/pages/_home.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#26 [Task] Disable days in the past of date input
  app/shared/components/FormEvent.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#28 [Task] Navigate when edit create event success
  app/routes/event.$eventId_.edit.tsx
  app/routes/event.create.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#27 [Task] Hide button delete in create event
  .gitignore
  app/routes/_index.tsx
  app/routes/events.$eventId.tsx
  app/routes/events.$eventId_.delete.tsx
  app/routes/events.$eventId_.edit.tsx
  app/routes/events.create.tsx
  app/routes/events.tsx
  app/shared/components/FormEvent.tsx
  prisma/schema.prisma
  stylesheet/pages/_home.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#30 [Task] Create add and back button
  app/routes/events.tsx
  assets/icons/ic-plus.svg
  stylesheet/modules/_icon.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#31 [Task] Create get all events api
  .gitignore
  app/routes/_index.tsx
  app/routes/events.$eventId.tsx
  app/routes/events.$eventId_.delete.tsx
  app/routes/events.$eventId_.edit.tsx
  app/routes/events.create.tsx
  app/routes/events.tsx
  app/server/event.server.ts
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/FormEvent.tsx
  app/shared/utils/formatNumberToDateString.ts
  app/shared/utils/types.server.ts
  prisma/schema.prisma
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#33 [Task] Modify navigation and delete function
  app/routes/events.$eventId_.delete.tsx
  app/routes/events.$eventId_.edit.tsx
  app/routes/events.create.tsx
  app/routes/events.tsx
  app/server/event.server.ts
  app/shared/components/FormEvent.tsx
  app/shared/constant/validator.ts
Labels: [Priority] 01 - Urgent, [Status] 03 - Review needed, [Type] Bug

#32 [Task] Separate sidebar component
  app/routes/events.tsx
  app/shared/components/Sidebar.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#34 [Task] Customize calendar cell
  app/routes/events.$eventId_.edit.tsx
  app/shared/components/CalendarWrapper.tsx
  stylesheet/modules/_calendar.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#36 [Fixbug] Fix bug: Navigate, toast and UI
  app/routes/events.$eventId_.delete.tsx
  app/routes/events.$eventId_.edit.tsx
  app/routes/events.create.tsx
  app/routes/events.tsx
  app/routes/login.tsx
  app/server/event.server.ts
  app/shared/components/FormEvent.tsx
  app/shared/components/Sidebar.tsx
  app/shared/constant/validator.ts
  app/shared/utils/getSearchParams.server.ts
  app/shared/utils/validators.server.ts
  assets/icons/ic-plus.svg
  stylesheet/modules/_form.scss
  stylesheet/modules/_icon.scss
  stylesheet/pages/_home.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Bug

#37 [Task] Create get all events in a day api, handle move forward and backward
  app/routes/events.tsx
  app/server/event.server.ts
  app/shared/components/CalendarWrapper.tsx
  app/shared/utils/convertDateString.ts
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#39 [Story-6] As a guest, I can filter event by days, weeks, months.
  app/routes/events.$eventId_.edit.tsx
  app/routes/events.tsx
  app/server/event.server.ts
  app/shared/components/CalendarWrapper.tsx
  app/shared/utils/convertDateString.ts
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#40 [Task] Create modal and modify delete event using confirm modal
  app/routes/events.$eventId.tsx
  app/routes/events.$eventId_.edit.tsx
  app/routes/events.tsx
  app/shared/components/FormEvent.tsx
  app/shared/components/Modal.tsx
  app/shared/components/modals_form/ConfirmDeleteEvent.tsx
  app/shared/helper/resolveModal.server.ts
  app/shared/utils/getSearchParams.server.ts
  stylesheet/base/_reset.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_modal.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#41 [Task] Create ui for event list
  app/shared/components/EventList.tsx
  app/shared/components/FormEvent.tsx
  app/shared/components/Sidebar.tsx
  app/shared/utils/convertDateString.ts
  app/shared/utils/date.ts
  assets/icons/ic-time.svg
  stylesheet/base/_base.scss
  stylesheet/base/_variables.scss
  stylesheet/modules/_icons.scss
  stylesheet/pages/_home.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#43 [Enhance Sprint-2] Enhancement
  app/routes/events.$eventId.tsx
  app/routes/events.$eventId_.edit.tsx
  app/routes/events.tsx
  app/routes/login.tsx
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/EventInfoItem.tsx
  app/shared/components/EventInfoList.tsx
  app/shared/components/EventList.tsx
  app/shared/components/FormEvent.tsx
  app/shared/components/Modal.tsx
  app/shared/components/Sidebar.tsx
  app/shared/components/modals_form/ConfirmDeleteEvent.tsx
  app/shared/components/modals_form/ShowEventDetail.tsx
  app/shared/helper/resolveModal.server.ts
  app/shared/utils/convertDateString.ts
  app/shared/utils/date.ts
  app/shared/utils/getSearchParams.server.ts
  assets/icons/ic-active.svg
  assets/icons/ic-bin.svg
  assets/icons/ic-calendar.svg
  assets/icons/ic-close.svg
  assets/icons/ic-copy.svg
  assets/icons/ic-desc.svg
  assets/icons/ic-meeting-link.svg
  assets/icons/ic-pen.svg
  assets/icons/ic-room.svg
  assets/icons/ic-time.svg
  assets/icons/ic-user.svg
  stylesheet/base/_base.scss
  stylesheet/base/_reset.scss
  stylesheet/base/_variables.scss
  stylesheet/layout/_all.scss
  stylesheet/layout/_calendar.scss
  stylesheet/layout/_sidebar.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_button.scss
  stylesheet/modules/_icon.scss
  stylesheet/modules/_icons.scss
  stylesheet/modules/_modal-event.scss
  stylesheet/modules/_modal.scss
  stylesheet/modules/_tooltip.scss
  stylesheet/pages/_home.scss
  stylesheet/state/_all.scss
  stylesheet/state/_display.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#48 [Enhance] Create soft delete event and redesign database
  app/routes/events.$eventId_.delete.tsx
  app/server/event.server.ts
  app/shared/components/CalendarWrapper.tsx
  app/shared/middleware/softDeleteEvent.ts
  app/shared/utils/formatNumberToDateString.ts
  prisma/schema.prisma
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#45 [Fix-bug] Fix extra week display in month view
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/Sidebar.tsx
  app/shared/components/modals_form/ConfirmDeleteEvent.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#46 [Fix-bug] Show edit and delete button if this event is current user event
  app/routes/events.tsx
  app/shared/components/modals_form/ShowEventDetail.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#49 [Task] Sync query param and ui when filter
  app/shared/components/CalendarWrapper.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#52 [Task] Responsive all page on tablet
  app/routes/login.tsx
  stylesheet/pages/_login.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#54 [Fixbug] Sprint 3
  app/routes/events.tsx
  app/routes/login.tsx
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/modals_form/ConfirmDeleteEvent.tsx
  app/shared/components/modals_form/ShowEventDetail.tsx
  stylesheet/pages/_login.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#47 [Fix-bug] Fix loading when user take action
  app/shared/components/EventList.tsx
  app/shared/components/Sidebar.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#55 [Fixbug] Fixbug/sprint 3
  app/shared/components/EventList.tsx
  app/shared/components/Sidebar.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#53 [Task] Modify login ui
  app/routes/login.tsx
  assets/images/login-bg.jpg
  stylesheet/pages/_login.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#56 [Task] Add mini calendar in sidebar
  README.md
  app/routes/events.tsx
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/MiniCalendar.tsx
  app/shared/components/Sidebar.tsx
  package-lock.json
  package.json
  stylesheet/modules/_all.scss
  stylesheet/modules/_mini-calendar.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#57 [Enhance] Adjust style for main calendar component
  app/routes/events.tsx
  app/shared/components/CalendarColumnHeader.tsx
  app/shared/components/CalendarEventBar.tsx
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/EventInfoItem.tsx
  app/shared/components/EventInfoList.tsx
  app/shared/components/EventList.tsx
  app/shared/utils/types.server.ts
  app/styles/app.css
  app/styles/app.css.map
  stylesheet/layout/_calendar.scss
  stylesheet/modules/_all.scss
  stylesheet/modules/_custom-event.scss
  stylesheet/state/_all.scss
  stylesheet/state/_border.scss
  stylesheet/state/_color.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#59 [Task] Show today event list to sidebar
  app/routes/events.tsx
  app/server/event.server.ts
  app/shared/components/Sidebar.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#62 [Fixbug] Fix login button color disabled
  app/styles/app.css
  stylesheet/modules/_button.scss
  stylesheet/pages/_login.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#61 [Task] Fix bug UI home screen
  app/routes/events.$eventId.tsx
  app/routes/login.tsx
  app/server/auth.server.ts
  app/shared/components/CalendarEventBar.tsx
  app/shared/components/CalendarWrapper.tsx
  app/shared/components/Sidebar.tsx
  app/shared/utils/types.server.ts
  app/styles/app.css
  app/styles/app.css.map
  stylesheet/layout/_calendar.scss
  stylesheet/layout/_sidebar.scss
  stylesheet/modules/_mini-calendar.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task
